import { Injectable, Logger } from '@nestjs/common'
import { prisma } from '../../database/prisma'
import { NotificationsService } from '../notifications/notifications.service'
import { RealtimeGateway } from '../realtime/realtime.gateway'
import { TASK_REMINDER_LEAD_MS } from './task-reminder.queue'

/// Wave 1 — service that finds tasks ready for a reminder and emits a
/// Notification to the assignee. Pulled out of the processor so the same code
/// runs from BullMQ AND from the controller's manual-trigger path (debug only).
@Injectable()
export class TaskReminderService {
  private readonly logger = new Logger(TaskReminderService.name)

  constructor(
    private readonly notifications: NotificationsService,
    private readonly realtime: RealtimeGateway,
  ) {}

  async runOnce(now: Date = new Date()): Promise<{ sent: number; scanned: number }> {
    const cutoff = new Date(now.getTime() + TASK_REMINDER_LEAD_MS)
    // Filtered, indexed scan: open tasks with a due date <= now+lead AND no
    // prior reminder. The (status, dueAt) index covers this query cheaply.
    const due = await prisma.task.findMany({
      where: {
        status: 'open',
        dueAt: { not: null, lte: cutoff },
        remindedAt: null,
      },
      orderBy: { dueAt: 'asc' },
      take: 200,
      select: {
        id: true,
        organizationId: true,
        assigneeUserId: true,
        creatorUserId: true,
        body: true,
        category: true,
        dueAt: true,
      },
    })

    let sent = 0
    for (const t of due) {
      try {
        await this.deliverOne(t)
        sent++
      } catch (err) {
        // Per-task failures (e.g. recipient no longer in org) must not abort
        // the batch — log and continue. NotificationsService.compose() throws
        // BadRequestException for self-recipient — should never happen here
        // since system-authored notifications use authorUserId: null.
        this.logger.warn(
          JSON.stringify({
            event: 'task_reminder.deliver_failed',
            taskId: t.id,
            message: (err as Error)?.message ?? 'unknown',
          }),
        )
      }
    }

    if (sent > 0 || due.length > 0) {
      this.logger.log(JSON.stringify({ event: 'task_reminder.tick', scanned: due.length, sent }))
    }
    return { sent, scanned: due.length }
  }

  private async deliverOne(t: {
    id: string
    organizationId: string
    assigneeUserId: string
    creatorUserId: string | null
    body: string
    category: string | null
    dueAt: Date | null
  }): Promise<void> {
    // Atomic CAS on remindedAt — gates against double delivery if two
    // workers race. updateMany returns 0 when another worker already stamped
    // it, in which case we skip the notification entirely.
    const stamp = new Date()
    const claimed = await prisma.task.updateMany({
      where: { id: t.id, status: 'open', remindedAt: null },
      data: { remindedAt: stamp },
    })
    if (claimed.count === 0) return

    const isSystemCompliance = t.category === 'compliance' && !t.creatorUserId
    const dueLabel = t.dueAt ? formatDueLabel(t.dueAt, stamp) : null
    // Compliance reminders generated by the scheduler render under the
    // "System" badge in the notifications bell. Their task bodies derive from
    // either the extracted document title (untrusted upload content) or a
    // manager-entered title — both are attacker-controllable. Keeping the
    // body OUT of the system-attributed notification text prevents phishing
    // payloads from masquerading as system security alerts. The user clicks
    // through to /tasks or /compliance to see the actual record.
    const noteBody = isSystemCompliance
      ? dueLabel
        ? `Compliance reminder — ${dueLabel}. Review in My Tasks.`
        : `Compliance reminder due. Review in My Tasks.`
      : dueLabel
        ? `Reminder — ${dueLabel}: ${truncate(t.body, 200)}`
        : `Reminder: ${truncate(t.body, 200)}`

    // Attribute the reminder to the task creator when the assignee didn't
    // create it themselves — otherwise the notification renders as "System"
    // and an attacker could spoof system-level alerts via attacker-controlled
    // task bodies. Self-created reminders stay system-authored (truly nobody
    // else originated them). Compose() also enforces a recipient !== author
    // guard, which our scan filter already prevents (creator==assignee falls
    // through to composeSystem below).
    // Reference lets the alerts row offer "Open task" + "Mark complete"
    // action buttons without parsing the task id out of the body.
    const reference = { kind: 'task' as const, id: t.id }
    if (t.creatorUserId && t.creatorUserId !== t.assigneeUserId) {
      // Attribute to the task creator so the recipient can see WHO set this
      // up, but flag as `automated` so the UI renders it with the gm
      // assistant treatment instead of "Elliot sent you a message."
      await this.notifications.compose(
        t.organizationId,
        t.creatorUserId,
        t.assigneeUserId,
        noteBody,
        { category: 'task', automated: true, reference },
      )
    } else {
      // Self-created task reminder — no human author. composeSystem already
      // marks `automated: true` by default.
      await this.notifications.composeSystem(t.organizationId, t.assigneeUserId, noteBody, {
        category: 'task',
        reference,
      })
    }

    // Refresh the assignee's My Tasks badge so remindedAt shows immediately
    // without waiting for a manual refetch.
    this.realtime.emitTaskUpserted([t.assigneeUserId], {
      kind: 'updated',
      id: t.id,
      assigneeUserId: t.assigneeUserId,
      status: 'open',
      dueAt: t.dueAt?.toISOString() ?? null,
      remindedAt: stamp.toISOString(),
    })
  }
}

function formatDueLabel(dueAt: Date, now: Date): string {
  const diffMs = dueAt.getTime() - now.getTime()
  const absHours = Math.round(Math.abs(diffMs) / (60 * 60 * 1000))
  if (diffMs < 0) {
    if (absHours < 24) return `overdue by ${absHours}h`
    const days = Math.round(absHours / 24)
    return `overdue by ${days}d`
  }
  if (absHours < 24) return `due in ${absHours}h`
  const days = Math.round(absHours / 24)
  return `due in ${days}d`
}

function truncate(s: string, max: number): string {
  return s.length <= max ? s : `${s.slice(0, max - 1)}…`
}
