"""Generators for the three TikZ appendix floats: A-F5, A-F6 and A-F7.

Every one runs the geometry assertions in `_tikz_assert` BEFORE writing, from the first
draft rather than after a defect. What they cannot check -- vertical extent, overfull
boxes, glyph collision -- goes on each float's check list for the compile.

A-F5  deployment architecture (Appendix A). Carries the deployment view F3 deliberately
      dropped: processes, stores and delivery surfaces. It must NOT restate F3's method
      pipeline, so no box here names a method step.
A-F6  injection protocol schematic (Appendix B). Grounding: Liu & Paparrizos (2024)
      Figs. 4-5.
A-F7  rolling-origin schematic (Appendix A), F2 demoted. Drawn TO SCALE from
      `eval/fold_vectors_L1_beer_hall.json` `folds[]`.
"""

from __future__ import annotations

from datetime import date

from _style import OUT, load
from _tikz_assert import (assert_no_negative_x, assert_no_overlap, assert_within,
                          label_box)

# The dissertation body is A4 with left=35mm, right=25mm (main.tex \newgeometry), so the
# text width is exactly 150mm. Every float is asserted against THAT, not against a
# convenient number: a figure checked at a width the document does not have is not checked.
TEXT_WIDTH_CM = 15.0
WIDTH_CM = 13.4
# A-F7 hangs a label off the right edge of every bar, so its drawing area has to be the
# text width MINUS that label. Asserting only the bars would repeat the F1 error of
# checking the objects that were modelled rather than all of them.
ORIGIN_LABEL_CM = 3.3
ORIGIN_BAR_CM = TEXT_WIDTH_CM - ORIGIN_LABEL_CM - 0.2


# --- A-F5: deployment architecture -------------------------------------------

def build_deployment() -> list[str]:
    """Three tiers, left to right: where data rests, what runs, how it reaches a person.

    Deliberately disjoint from F3. F3 answers "what is the method"; this answers "what is
    deployed". Sharing a box between them would be the two-figures-for-one-flow cost the
    programme rejected when it merged them.
    """
    tiers = [
        ("stores", 0.0, 3.9, "Stores", [
            "DuckDB warehouse\\\\{\\lunefigannot 24 tables, Square exports}",
            "Parquet fold vectors\\\\{\\lunefigannot per-venue, per-rung}",
            "Zotero + NotebookLM\\\\{\\lunefigannot corpus, not runtime}",
        ]),
        ("services", 4.75, 3.9, "Services", [
            "FastAPI brain\\\\{\\lunefigannot 9 endpoints}",
            "NestJS API\\\\{\\lunefigannot 8 registered agent tools}",
            "Scheduled jobs\\\\{\\lunefigannot nightly refresh}",
        ]),
        ("surfaces", 9.5, 3.9, "Surfaces", [
            "Agent chat\\\\{\\lunefigannot in-product}",
            "WhatsApp delivery\\\\{\\lunefigannot Twilio}",
            "Operator inbox\\\\{\\lunefigannot notes and tasks}",
        ]),
    ]

    boxes = [label_box(x + w / 2, w, name) for name, x, w, _, _ in tiers]
    assert_no_overlap(boxes, what="A-F5 tiers", min_gap=0.5)
    assert_within(boxes, what="A-F5 tiers", lo=0.0, hi=TEXT_WIDTH_CM)

    lines = [
        "% GENERATED by figures/fig_appendix_tikz.py -- do not hand-edit.",
        "% A-F5 deployment architecture, Appendix A. Displaced from F3, which carries the",
        "% METHOD pipeline; nothing here names a method step. Grounding: Lu et al. (2024),",
        "% Fu et al. (2026) PRISM -- both draw the deployed system as tiered blocks.",
        "\\begin{tikzpicture}[font=\\small,",
        "    tier/.style={draw,line width=\\lunerule,rounded corners=2pt,fill=lunepaper,minimum width=3.9cm,"
        "align=center,inner sep=4pt,anchor=north west,font=\\lunefiglabel},",
        "    hd/.style={font=\\lunefiglabel\\bfseries,anchor=north},",
        "    fl/.style={-{Stealth[length=4pt]},lunegrey2}]",
    ]
    for name, x, w, heading, items in tiers:
        lines.append(f"  \\node[hd] at ({x + w / 2:.3f},0.45) {{{heading}}};")
        y = 0.0
        for j, item in enumerate(items):
            lines.append(f"  \\node[tier] ({name}{j}) at ({x:.3f},{y:.3f})"
                         f" {{{item}}};")
            y -= 1.15
    for j in range(3):
        lines.append(f"  \\draw[fl] (stores{j}.east) -- (services{j}.west);")
        lines.append(f"  \\draw[fl] (services{j}.east) -- (surfaces{j}.west);")
    lines.append("\\end{tikzpicture}")
    assert_no_negative_x(lines, what="A-F5")
    return lines


# --- A-F6: injection protocol ------------------------------------------------

def build_injection() -> list[str]:
    """Control arm against realistic arm, drawn rather than narrated.

    The point the schematic has to make is that both arms inject into the SAME held-out
    stream and are scored by the same detector, so a difference between them is a
    property of the injection and not of the evaluation.
    """
    stages = [
        ("held-out\\\\stream", 0.0, 2.3),
        ("inject at\\\\onset $t_0$", 3.1, 2.3),
        ("detector\\\\(CUSUM + $m_{\\mathrm{brk}}$-of-$n_{\\mathrm{win}}$)", 6.2, 2.9),
        ("caught /\\\\missed", 9.9, 2.3),
    ]
    boxes = [label_box(x + w / 2, w, lab.replace("\\\\", " ")) for lab, x, w in stages]
    assert_no_overlap(boxes, what="A-F6 stages", min_gap=0.5)
    assert_within(boxes, what="A-F6 stages", lo=0.0, hi=TEXT_WIDTH_CM)

    lines = [
        "% GENERATED by figures/fig_appendix_tikz.py -- do not hand-edit.",
        "% A-F6 injection protocol, Appendix B. Grounding: Liu & Paparrizos (2024) Figs. 4-5.",
        "\\begin{tikzpicture}[font=\\small,",
        "    st/.style={draw,line width=\\lunerule,rounded corners=2pt,align=center,inner sep=4pt,"
        "minimum height=1.0cm,anchor=north west,font=\\lunefiglabel},",
        "    arm/.style={draw,line width=\\lunerule,dashed,rounded corners=2pt,align=center,inner sep=3pt,"
        "anchor=north west,font=\\lunefiglabel,text=lunegrey2},",
        "    fl/.style={-{Stealth[length=4pt]},lunegrey2}]",
    ]
    for i, (lab, x, w) in enumerate(stages):
        fill = "fill=lunegold!18" if i == 2 else "fill=lunepaper"
        lines.append(f"  \\node[st,{fill},minimum width={w:.3f}cm] (s{i})"
                     f" at ({x:.3f},0) {{{lab}}};")
    for i in range(3):
        lines.append(f"  \\draw[fl] (s{i}.east) -- (s{i + 1}.west);")
    # The two arms differ only in what is injected; everything downstream is shared.
    lines += [
        "  \\node[arm,minimum width=2.3cm] (ctrl) at (3.1,1.15)"
        " {control arm\\\\{\\lunefigannot synthetic step / spike}};",
        "  \\node[arm,minimum width=2.3cm] (real) at (3.1,-1.35)"
        " {realistic arm\\\\{\\lunefigannot replayed historical event}};",
        "  \\draw[fl,lunegrey] (ctrl.south) -- (s1.north);",
        "  \\draw[fl,lunegrey] (real.north) -- (s1.south);",
        # y=-2.6 and a wrapping text width, not y=-2.1 on one line. The `realistic arm'
        # box is anchored north at -1.35 and its two lines carry it to about -2.25, so the
        # old position printed the sentence straight THROUGH that box; the single long line
        # also overfull'd the text block by 9.56 pt. Both were only visible once compiled.
        "  \\node[font=\\lunefigsecond,text=lunegrey2,anchor=north west,text width=13.4cm,align=left]"
        " at (0,-2.6)"
        " {Both arms inject into the same held-out stream and are scored by the same"
        " detector, so any difference is a property of the injection.};",
        "\\end{tikzpicture}",
    ]
    assert_no_negative_x(lines, what="A-F6")
    return lines


# --- A-F7: rolling origin, to scale ------------------------------------------

def _origin_inset(folds: list[dict], y_top: float) -> list[str]:
    """A magnified window over three CONSECUTIVE origins.

    Without this the figure fails its own argument. At full span a seven-day forecast
    block is 1.7 mm wide and consecutive blocks are offset by 0.25 mm, so the overlap --
    the entire reason the block bootstrap uses a block length of seven -- is invisible.
    The main panel establishes the expanding window to scale; the inset establishes the
    overlap, at a stated magnification rather than by silently redrawing the same thing
    bigger.
    """
    first = date.fromisoformat(folds[0]["test_start"]).toordinal()
    last = date.fromisoformat(folds[2]["test_end"]).toordinal()
    days = last - first + 1               # 9 days: three 7-day blocks at a 1-day step
    width = 6.6
    per_day = width / days

    def ix(d: str) -> float:
        return (date.fromisoformat(d).toordinal() - first) * per_day

    lines = [
        "  %% inset: three consecutive origins, magnified so the overlap is legible",
        f"  \\node[font=\\lunefiglabel\\itshape,text=lunegrey2,anchor=north west]"
        f" at (0,{y_top:.3f}) {{three consecutive origins, magnified}};",
    ]
    # 0.78, not 0.34. A \lunefiglabel line under the document's \linespread{1.5} descends
    # about 0.40 cm below its anchor=north point (measured off the compile: F1's two-line
    # label runs 1.05 cm with a 0.647 cm baseline step, so one line is ~0.40 cm). At 0.34
    # the first forecast block started ABOVE the title's own baseline, and because the
    # blocks are emitted after the title node they painted straight over it -- the inset
    # title was illegible in the first rendered compile. 0.78 clears the descender and
    # leaves ~0.12 cm of air.
    yy = y_top - 0.78
    for i in range(3):
        f = folds[i]
        x0, x1 = ix(f["test_start"]), ix(f["test_end"])
        lines.append(f"  \\node[te,minimum width={x1 - x0 + per_day:.3f}cm]"
                     f" at ({x0:.3f},{yy:.3f}) {{}};")
        lines.append(f"  \\node[el,font=\\lunefigannot] at ({width + 0.25:.3f},{yy + 0.13:.3f})"
                     f" {{origin {i + 1}: {f['test_start']} to {f['test_end']}}};")
        yy -= 0.40
    # The shared span between the first and third block, which is the quantity that matters.
    shade_lo, shade_hi = ix(folds[2]["test_start"]), ix(folds[0]["test_end"]) + per_day
    # Top edge follows the first block, not the title: at y_top-0.30 the shading also ran
    # under the title text and greyed it further.
    lines.insert(1, f"  \\fill[lunegold!18] ({shade_lo:.3f},{yy - 0.02:.3f}) rectangle "
                    f"({shade_hi:.3f},{y_top - 0.52:.3f});")
    lines.append(f"  \\node[font=\\lunefigannot,text=lunegrey2,anchor=north] at "
                 f"({(shade_lo + shade_hi) / 2:.3f},{yy + 0.02:.3f})"
                 " {shared by all three};")
    boxes = [("inset blocks", 0.0, width + 0.2),
             ("inset labels", width + 0.25, width + 0.25 + 4.4)]
    assert_within(boxes, what="A-F7 inset", lo=0.0, hi=TEXT_WIDTH_CM)
    return lines


def build_origins() -> list[str]:
    """Expanding-window rolling origin at a one-day step, drawn from the real folds.

    Only a sample of origins is drawn -- 273 bars at this width would be 0.05 cm apart and
    render as a solid block -- but the sampled bars are at their true coordinates, so the
    expansion rate and the seven-day forecast block are to scale rather than stylised.
    The overlap between consecutive forecast blocks is the whole reason the block
    bootstrap uses a block length of seven, and it is what a constants table cannot show.
    """
    folds = load("eval/fold_vectors_L1_beer_hall.json")["folds"]
    start = date.fromisoformat(folds[0]["train_end"])
    # `train_end` of the first fold is 120 days after the series begins.
    origin0 = start.toordinal() - folds[0]["n_train"]
    span = date.fromisoformat(folds[-1]["test_end"]).toordinal() - origin0

    def x(d: str) -> float:
        return ORIGIN_BAR_CM * (date.fromisoformat(d).toordinal() - origin0) / span

    shown = [0, 1, 2, len(folds) // 2, len(folds) - 2, len(folds) - 1]
    lines = [
        "% GENERATED by figures/fig_appendix_tikz.py -- do not hand-edit.",
        "% A-F7 rolling-origin schematic, Appendix A (F2 demoted -- see 07 section 0).",
        "% Source: brain/eval/fold_vectors_L1_beer_hall.json folds[]. TO SCALE.",
        "% Grounding: Meyer et al. (2026) Fig. 1(a) -- rolling origin as a staircase of",
        "% stacked timelines, training windows shifting right, forecast targets following.",
        "\\begin{tikzpicture}[font=\\small,",
        "    tr/.style={draw=lunegrey,line width=\\lunerule,fill=lunegold!18,minimum height=0.26cm,inner sep=0pt,"
        "anchor=south west},",
        "    te/.style={draw=luneink!75,line width=\\lunerule,fill=lunegold!62,minimum height=0.26cm,inner sep=0pt,"
        "anchor=south west},",
        "    el/.style={font=\\lunefiglabel,text=lunegrey2,anchor=west}]",
    ]
    y = 0.0
    for rank, i in enumerate(shown):
        f = folds[i]
        x_tr_end, x_te0, x_te1 = x(f["train_end"]), x(f["test_start"]), x(f["test_end"])
        if rank == 3:
            lines.append(f"  \\node[el] at (0.15,{y + 0.13:.3f}) {{$\\vdots$}};")
            y -= 0.42
        lines.append(f"  \\node[tr,minimum width={x_tr_end:.3f}cm] at (0,{y:.3f}) {{}};")
        lines.append(f"  \\node[te,minimum width={max(x_te1 - x_te0, 0.06):.3f}cm]"
                     f" at ({x_te0:.3f},{y:.3f}) {{}};")
        lines.append(f"  \\node[el] at ({ORIGIN_BAR_CM + 0.12:.3f},{y + 0.13:.3f})"
                     f" {{origin {i + 1}, $n_{{\\mathrm{{train}}}}={f['n_train']}$}};")
        y -= 0.42

    # The right-hand origin labels are part of the drawing's extent, so they are asserted
    # with the bars rather than left out of the model.
    boxes = [("training bar", 0.0, x(folds[-1]["train_end"])),
             ("last forecast block", x(folds[-1]["test_start"]), x(folds[-1]["test_end"])),
             ("origin labels", ORIGIN_BAR_CM + 0.12,
              ORIGIN_BAR_CM + 0.12 + ORIGIN_LABEL_CM)]
    assert_within(boxes, what="A-F7", lo=0.0, hi=TEXT_WIDTH_CM)

    lines += [
        f"  \\draw[->,luneink!80] (0,{y + 0.28:.3f}) -- ({ORIGIN_BAR_CM + 0.2:.2f},{y + 0.28:.3f})",
        "        node[below left,font=\\lunefiglabel,text=lunegrey2]{calendar time};",
    ]
    y -= 0.30
    lines += _origin_inset(folds, y)
    lines += [
        f"  \\node[font=\\lunefigsecond,text=lunegrey2,anchor=north west,text width="
        f"{TEXT_WIDTH_CM - 0.2:.1f}cm] at (0,{y - 2.35:.3f})"
        " {273 origins at the Beer Hall, 260 at Ellel, 205 at Two River Taps; minimum"
        " train 120 days, horizon 7, step 1 day. The inset magnifies three consecutive"
        " origins: each forecast block shares six of its seven days with the next, which"
        " is why the origins are not independent and why the block bootstrap uses a block"
        " length of seven.};",
        "\\end{tikzpicture}",
    ]
    assert_no_negative_x(lines, what="A-F7")
    return lines


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, builder in (("a_f5_deployment", build_deployment),
                          ("a_f6_injection", build_injection),
                          ("a_f7_origins", build_origins)):
        path = OUT / f"{name}.tex"
        path.write_text("\n".join(builder()) + "\n")
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
