"""F1 `fig:blocks` -- the four-block split, emitted as TikZ from the measured spans.

The highest-priority new float. The defect it documents is TEMPORAL: the superseded
two-way split let one span do two jobs, so the calibration scores were drawn from data
the forecaster had already been fitted on. Only a time axis shows that; a flowchart
shows dependency and not ordering, which is the whole content of the correction.

Emitted as TikZ rather than drawn in matplotlib so the labels typeset in the document's
own font and remain selectable, and because there is no data series here -- only dates.
The bar geometry is computed from brain/hierarchy/block_spans.json, so the drawing is to
scale rather than schematic.

Grounding: Kaas et al. (2026) Fig. 6 (horizontal block diagram, time on x, training /
ignored / unseen spans distinguished); Hewamalage et al. (2023) Fig. 10 (two partitioning
strategies contrasted as stylised horizontal timelines) -- the before/after construction
used here.

Writes figures/out/fig_blocks.tex for \\input{} into the Methods chapter.
"""

from __future__ import annotations

from datetime import date

from _style import OUT, load

WIDTH_CM = 13.4
ROW_H = 0.62
FILL = {
    "fit": ("black!8", "black!45"),
    "validation": ("black!22", "black!55"),
    "calibration": ("black!38", "black!65"),
    "test": ("black!58", "black!80"),
}
SHORT = {"fit": "fit", "validation": "validate", "calibration": "calibrate", "test": "test"}


def _d(s: str) -> date:
    return date.fromisoformat(s)


def main() -> None:
    spans = load("hierarchy/block_spans.json")
    start, end = _d(spans["calendar_start"]), _d(spans["calendar_end"])
    total = (end - start).days

    def x(day: str) -> float:
        return WIDTH_CM * (_d(day) - start).days / total

    lines: list[str] = [
        "% GENERATED by figures/fig_blocks.py -- do not hand-edit.",
        "% Source: brain/hierarchy/block_spans.json (.venv-forecast, provenance-stamped).",
        "\\begin{tikzpicture}[font=\\small]",
        "  \\tikzset{blk/.style={draw,minimum height=%.2fcm,inner sep=0pt,anchor=south west}}"
        % ROW_H,
    ]

    # Row 1: the superseded two-way split, so the reader sees what changed.
    cut = x(spans["blocks"][2]["start"])
    lines += [
        "  %% superseded two-way split",
        f"  \\node[blk,fill=black!6,draw=black!35,text=black!60,minimum width={cut:.3f}cm]"
        f" at (0,2.35) {{\\scriptsize fit \\emph{{and}} calibrate}};",
        f"  \\node[blk,fill=black!30,draw=black!55,minimum width={WIDTH_CM - cut:.3f}cm]"
        f" at ({cut:.3f},2.35) {{\\scriptsize test}};",
        "  \\node[anchor=east,text=black!55] at (-0.15,2.66) "
        "{\\scriptsize\\itshape superseded};",
        f"  \\draw[decorate,decoration={{brace,amplitude=3pt}},black!55] "
        f"(0,{2.35 + ROW_H + 0.08:.2f}) -- ({cut:.3f},{2.35 + ROW_H + 0.08:.2f}) "
        "node[midway,above,yshift=-1pt,text=black!55]{\\scriptsize one span, two jobs};",
    ]

    # Row 2: the adopted four-block split, each block doing exactly one job.
    lines.append("  %% adopted four-block split")
    for blk in spans["blocks"]:
        x0, x1 = x(blk["start"]), x(blk["end"])
        fill, draw = FILL[blk["block"]]
        w = max(x1 - x0, 0.05)
        # The bar carries fill only. A label typeset INSIDE a 1.85 cm block would
        # overflow it and collide with its neighbour, and the three narrow blocks abut.
        lines.append(
            f"  \\node[blk,fill={fill},draw={draw},minimum width={w:.3f}cm]"
            f" at ({x0:.3f},1.05) {{}};")
        lines.append(
            f"  \\node[anchor=north,align=center,text width=2.45cm]"
            f" at ({x0 + w / 2:.3f},0.98) {{\\scriptsize\\textbf{{{SHORT[blk['block']]}}}"
            f" ($n{{=}}{blk['n_days']}$)\\\\[-1pt]"
            f" {{\\scriptsize\\color{{black!60}}{blk['job']}}}}};")

    lines += [
        "  \\node[anchor=east] at (-0.15,1.36) {\\scriptsize\\itshape adopted};",
        "  %% time axis",
        f"  \\draw[->,black!70] (0,0.05) -- ({WIDTH_CM + 0.25:.2f},0.05);",
    ]
    for label in (spans["calendar_start"], spans["blocks"][1]["start"],
                  spans["blocks"][2]["start"], spans["blocks"][3]["start"],
                  spans["calendar_end"]):
        lines.append(f"  \\draw[black!70] ({x(label):.3f},0.05) -- ({x(label):.3f},-0.06)"
                     f" node[below,black!70]{{\\scriptsize {label}}};")

    lines += [
        "  %% the disjointness that IS the guarantee",
        f"  \\draw[<->,black!75] ({x(spans['blocks'][0]['end']):.3f},1.98) -- "
        f"({x(spans['blocks'][2]['start']):.3f},1.98)"
        " node[midway,above,yshift=-2pt]{\\scriptsize fit ends strictly before calibration"
        " begins};",
        "\\end{tikzpicture}",
    ]

    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / "fig_blocks.tex"
    path.write_text("\n".join(lines) + "\n")
    print(f"wrote {path}")
    print(f"  spans: " + ", ".join(
        f"{b['block']} {b['start']}..{b['end']} n={b['n_days']}" for b in spans["blocks"]))


if __name__ == "__main__":
    main()
