"""F1 `fig:blocks` -- the four-block split, emitted as TikZ from the measured spans.

The highest-priority new float. The defect it documents is TEMPORAL: the superseded
two-way split let one span do two jobs, so the calibration scores were drawn from data
the forecaster had already been fitted on. Only a time axis shows that; a flowchart
shows dependency and not ordering, which is the whole content of the correction.

Emitted as TikZ rather than drawn in matplotlib so the labels typeset in the document's
own font and remain selectable, and because there is no data series here -- only dates.
The bar geometry is computed from brain/hierarchy/block_spans.json, so the drawing is to
scale rather than schematic.

Grounding: Kaas et al. (2026) Fig. 6 (horizontal block diagram, time on x, training /
ignored / unseen spans distinguished); Hewamalage et al. (2023) Fig. 10 (two partitioning
strategies contrasted as stylised horizontal timelines) -- the before/after construction
used here.

Writes figures/out/fig_blocks.tex for \\input{} into the Methods chapter.
"""

from __future__ import annotations

from datetime import date

from _style import OUT, load
from _tikz_assert import assert_within

# The dissertation is 12pt `report` on A4 with left=35mm right=25mm and \linespread{1.5}
# (main.tex). Text width is 150mm. This figure's clearances were first computed against an
# 11pt article in landscape with 15mm margins -- the geometry of the compile PROOF rather
# than of the document -- which made every one of them a check against the wrong target.
TEXT_WIDTH_CM = 15.0
WIDTH_CM = 13.4
ROW_H = 0.62
# Clearance between adjacent below-bar labels. Small, because the narrow blocks are
# 1.85 cm wide and the longest word left on the figure ("calibrate") is about 1.15 cm
# at \scriptsize -- the label must stay wider than that or it overfulls instead.
GUTTER_CM = 0.09
# Height of a two-line \scriptsize label under the DOCUMENT's leading, not the proof's.
#
# THIS IS AN ESTIMATE, NOT A MEASUREMENT. Nothing here has been read off a rendered PDF.
# It is derived: 12pt base makes \scriptsize 8pt on a ~9.5pt baseline; \linespread{1.5}
# takes that to ~14.25pt, so two lines plus ascender and descender is about 0.72 cm --
# roughly a quarter taller than the same label in the 11pt proof, which is why the
# clearance first reported at 3.3 mm is in fact 2.2 mm. Label height is downstream of line
# breaking, so it sits on the compile check list rather than in an assertion.
#
# The three inputs are BASE SIZE, \scriptsize's ratio, and \linespread. If any of them
# changes in main.tex, this constant is wrong and must be re-derived -- it is not a number
# that was found to work, and it should not be treated as one.
LABEL_H_CM = 0.72
LABEL_TOP_Y = 0.98
AXIS_MARGIN_CM = 0.22
AXIS_Y = round(LABEL_TOP_Y - LABEL_H_CM - AXIS_MARGIN_CM, 2)
FILL = {
    "fit": ("black!8", "black!45"),
    "validation": ("black!22", "black!55"),
    "calibration": ("black!38", "black!65"),
    "test": ("black!58", "black!80"),
}
SHORT = {"fit": "fit", "validation": "validate", "calibration": "calibrate", "test": "test"}


def _d(s: str) -> date:
    return date.fromisoformat(s)


def _assert_no_label_overlap(spans, x) -> None:
    """Fail the build if two below-bar labels would occupy the same horizontal span.

    This is here because the overlap was missed once by eye and by reasoning about the
    figure, and found only by doing the arithmetic: a 2.45 cm label on 1.885 cm centres
    overlaps its neighbour by 0.565 cm whatever text it holds. Geometry a generator can
    check should not be left to a person looking at a render.
    """
    boxes = []
    for blk in spans["blocks"]:
        x0, x1 = x(blk["start"]), x(blk["end"])
        w = max(x1 - x0, 0.05)
        half = min(2.45, w - GUTTER_CM) / 2
        centre = x0 + w / 2
        boxes.append((blk["block"], centre - half, centre + half))
    for (a, _, a_hi), (b, b_lo, _) in zip(boxes, boxes[1:]):
        if b_lo < a_hi:
            raise SystemExit(
                f"REFUSING to write: labels '{a}' and '{b}' overlap by "
                f"{a_hi - b_lo:.3f} cm. Widen the blocks or narrow the labels.")


def _assert_no_left_overhang(lines: list[str]) -> None:
    """Nothing may be placed at a negative x.

    With `\\noindent` the picture origin IS the text margin, so a node hung off the left
    lands in the page margin as an overfull box rather than being reflowed.
    """
    bad = [ln for ln in lines if " at (-" in ln]
    if bad:
        raise SystemExit("REFUSING to write: node placed left of the origin:\n  "
                         + "\n  ".join(bad))


def main() -> None:
    spans = load("hierarchy/block_spans.json")
    start, end = _d(spans["calendar_start"]), _d(spans["calendar_end"])
    total = (end - start).days

    def x(day: str) -> float:
        return WIDTH_CM * (_d(day) - start).days / total

    lines: list[str] = [
        "% GENERATED by figures/fig_blocks.py -- do not hand-edit.",
        "% Source: brain/hierarchy/block_spans.json (.venv-forecast, provenance-stamped).",
        "\\begin{tikzpicture}[font=\\small]",
        "  \\tikzset{blk/.style={draw,minimum height=%.2fcm,inner sep=0pt,anchor=south west}}"
        % ROW_H,
    ]

    # Row 1: the superseded two-way split, so the reader sees what changed.
    cut = x(spans["blocks"][2]["start"])
    lines += [
        "  %% superseded two-way split",
        # The row tags live INSIDE the widest bar of each row. Set outside on the left
        # (`anchor=east` at a negative x) they extended about 1.5 cm past the picture
        # origin, which with \noindent is the text margin -- an overfull \hbox and glyphs
        # in the page margin, and TikZ does not reflow to save you from it.
        f"  \\node[blk,fill=black!6,draw=black!35,text=black!60,minimum width={cut:.3f}cm]"
        f" at (0,2.35) {{\\scriptsize\\itshape superseded:\\/"
        f" \\upshape fit \\emph{{and}} calibrate}};",
        f"  \\node[blk,fill=black!30,draw=black!55,minimum width={WIDTH_CM - cut:.3f}cm]"
        f" at ({cut:.3f},2.35) {{\\scriptsize test}};",
        f"  \\draw[decorate,decoration={{brace,amplitude=3pt}},black!55] "
        f"(0,{2.35 + ROW_H + 0.08:.2f}) -- ({cut:.3f},{2.35 + ROW_H + 0.08:.2f}) "
        "node[midway,above,yshift=-1pt,text=black!55]{\\scriptsize one span, two jobs};",
    ]

    # Row 2: the adopted four-block split, each block doing exactly one job.
    lines.append("  %% adopted four-block split")
    for blk in spans["blocks"]:
        x0, x1 = x(blk["start"]), x(blk["end"])
        fill, draw = FILL[blk["block"]]
        w = max(x1 - x0, 0.05)
        # The bar carries fill only, plus the row tag on the widest block. A label typeset
        # INSIDE a 1.85 cm block would overflow it; a fixed-width label BELOW it overlaps
        # its neighbour instead, because the label centres are spaced by the block widths.
        # So the label width is derived from the block it belongs to, less a gutter, which
        # makes non-overlap a property of the construction rather than of a chosen constant.
        lines.append(
            f"  \\node[blk,fill={fill},draw={draw},minimum width={w:.3f}cm]"
            f" at ({x0:.3f},1.05) {{}};")
        if blk["block"] == "fit":
            # Left-aligned inside the bar, not centred. Centred it sits at the same x as
            # the `fit` label directly below and the pair reads as a two-line caption for
            # that one block rather than as a tag for the whole row.
            lines.append(
                f"  \\node[anchor=west,text=black!55] at ({x0 + 0.1:.3f},{1.05 + ROW_H / 2:.3f})"
                " {\\scriptsize\\itshape adopted};")
        # Name and n only, on two lines. The role descriptions used to sit here and were
        # the reason the label needed width; at 1.76 cm "conformal scores + reconciliation
        # weights" wraps to four or five lines, and the whole label then descends through
        # the time axis at y = 0.05 and into the date labels below it. Narrowing the label
        # to fix the horizontal overlap made that worse. The descriptions are explanation
        # rather than labelling, so they moved into the caption, which removes the
        # constraint instead of accommodating it. `blk["job"]` is the caption's source.
        label_w = min(2.45, w - GUTTER_CM)
        lines.append(
            f"  \\node[anchor=north,align=center,text width={label_w:.3f}cm]"
            f" at ({x0 + w / 2:.3f},{LABEL_TOP_Y}) {{\\scriptsize\\textbf{{{SHORT[blk['block']]}}}"
            f"\\\\[-2pt] $n{{=}}{blk['n_days']}$}};")

    lines += [
        "  %% time axis -- placed below the computed label extent, not at a coordinate",
        "  %% that cleared it once under a different document's leading.",
        f"  \\draw[->,black!70] (0,{AXIS_Y}) -- ({WIDTH_CM + 0.25:.2f},{AXIS_Y});",
    ]
    for label in (spans["calendar_start"], spans["blocks"][1]["start"],
                  spans["blocks"][2]["start"], spans["blocks"][3]["start"],
                  spans["calendar_end"]):
        lines.append(f"  \\draw[black!70] ({x(label):.3f},{AXIS_Y}) -- ({x(label):.3f},{AXIS_Y - 0.11:.2f})"
                     f" node[below,black!70]{{\\scriptsize {label}}};")

    lines += [
        "  %% the disjointness that IS the guarantee",
        f"  \\draw[<->,black!75] ({x(spans['blocks'][0]['end']):.3f},1.98) -- "
        f"({x(spans['blocks'][2]['start']):.3f},1.98)"
        " node[midway,above,yshift=-2pt]{\\scriptsize fit ends strictly before calibration"
        " begins};",
        "\\end{tikzpicture}",
    ]

    _assert_no_label_overlap(spans, x)
    _assert_no_left_overhang(lines)
    # The whole drawing, axis arrow included, must sit inside the DOCUMENT's text width.
    assert_within([("picture", 0.0, WIDTH_CM + 0.25)], what="F1", lo=0.0, hi=TEXT_WIDTH_CM)

    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / "fig_blocks.tex"
    path.write_text("\n".join(lines) + "\n")
    print(f"wrote {path}")
    print("  spans: " + ", ".join(
        f"{b['block']} {b['start']}..{b['end']} n={b['n_days']}" for b in spans["blocks"]))
    # The roles moved off the figure and into the caption, so they are printed here.
    # The caption's source is this artefact; a caption written from memory drifts from it.
    print("  FOR THE CAPTION — " + "; ".join(
        f"{b['block']}: {b['job']}" for b in spans["blocks"]))


if __name__ == "__main__":
    main()
